### ISSUE TITLE
IBC Crash after succesful login

### ISSUE THREAD

**Issue by eyalco** [UnusualAlpha/ib-gateway-docker#102]
**Bug**
version of ib-gateway 10.24.1f
After succesfull Login and 2FA. IBC shuts down the docker with an error

**To Reproduce**
1. Cloned the repo
2. changed the version in \latest\Dockerfile to 10.24.1f in two places in the file , as needed.
3. The build is ok
4. I ran the docker (I had to get in with VNC and had to manually enter password and userid but this is for another issue)
5. gave 2FA
6. login successfully
7. CRASH

**Expected behavior**
After login I should be able to trade

**Container logs**

2023-09-05 17:16:26:958 IBC: Detected dialog entitled:  U11XXXXXX TWS Configuration; event=Focused
2023-09-05 17:16:26:958 IBC: Detected frame entitled: Starting application...; event=Closed
2023-09-05 17:16:26:958 IBC: Login has completed
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2023-09-05 17:16:26:958 IBC: An exception has occurred:
java.lang.NullPointerException
	at ibcalpha.ibc.LoginManager.setLoginState(Unknown Source)
	at ibcalpha.ibc.SplashFrameHandler.handleWindow(Unknown Source)
	at ibcalpha.ibc.TwsListener.lambda$eventDispatched$0(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2023-09-05 17:16:26:959 IBC: Exiting with exit code=1100
IBC returned exit status 76
Renaming TWS or Gateway .exe file to original name
Gateway finished
**Versions (please complete the following information):**
 - OS: linux
 - Docker version: [e.g. chrome, safari]

**Additional context**

**Comment by eyalco** [comment]
Changed to version 3.18 for IBC and it works

**Comment by eyalco** [comment]
Relating to this bug. The current latest ib-gateway version on this github is 1022. It does not work with IBC version 3.16. It should at least be updated to version 3.17 or 3.18.
As well as adding the latest verfion 1024.1f.
All prior version cannot be used as of 30/8/2023.

**Comment by gnzsnz** [comment]
@eyalco  looks like this image is not been maintained any more.

I have cloned it and done a few changes needed to support latest features in IB gateway and IBC

you can find it here --> https://github.com/gnzsnz/ib-gateway-docker/pkgs/container/ib-gateway
